sudo: false

language: node_js
node_js:
  - 6
  - 8
  - 10

before_install:
  - npm install coveralls

script: "npm run test:coverage"

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
